# Ritta deployment configuration

# Local project directory
local_project_root: ./

# Directory where the project will be deployed
remote_project_root: /root/mellalanding/

setup_config:
  # Setup script to run on the server
  # You can modify this, default is set up with apt package manager and default installs
  script: ./rittaScript.sh

source:
  # "existing" = use the current project(the project is already on your vps)
  # "git"      = clone from a repository
  type: git

  # Uncomment these when using git:
  repository: git@github.com:MellaSoftwareSolutions/mellasoftware.git
  branch: main


# Vps info and your ssh key for log in
server:                                                                     
  host: 161.97.156.181                                                      
  user: root                                                                
  port: 22                                                                  
  key: ~/.ssh/id_ed25519

# Optional health check command if you have
health:
  command: ""


# Files to copy to the server
# Add as many files as needed
file:
  # - from: .env
  #   to: .env

  # - from: ./config/app.yaml
  #   to: config/app.yaml


# Your application specific build command 
build:
  command: "docker build -t mella-image ."

# Your application specific run command
run:
  command: "docker run -d -p 3033:3033 --name mella-container mella-image"


# Domains to expose through the reverse proxy(optional)
# Add as many domains as needed
domains:
  - host: mellasoftware.org
    port: 3033
    tls: true


proxy:
  #leave empty if you don't want to use a reverse proxy
  provider: Nginx

tls:
  #leave empty if you don't want to use TLS
  provider: letsencrypt
  email: "mellasoftwaresolutions@gmail.com"
