const work = [
  ['AdVouch', 'In-house · Live', 'A marketplace for vouched advertising, identity checks, and campaign payments.'],
  ['Operations System', 'Client · Internal', 'Branches, inventory, staff, and daily operations brought into one place.'],
  ['Booking Platform', 'Client · Web + SMS', 'Online booking, staff calendars, and automated reminders.'],
  ['Field App', 'Client · Mobile', 'A mobile system for teams working outside the office.'],
]
const services = ['Custom software', 'Dedicated teams', 'Product design', 'Web & mobile', 'Integrations', 'Support & improvements']
const process = [['01', 'Understand', 'We learn the problem, users, constraints, and what actually needs to be built.'], ['02', 'Build', 'Design and engineering happen together. You see working software early.'], ['03', 'Ship', 'We get it into production instead of keeping it trapped in development.'], ['04', 'Improve', 'We stay involved to fix, maintain, and build the next version.']]
function Arrow() { return <span aria-hidden="true">↗</span> }
function Link({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) { return <a className={`text-link ${className}`} href={href}>{children} <Arrow /></a> }

export default function Page() {
  return <main id="top">
    <header className="site-header"><a href="#top" className="brand">Mella<span>.</span></a><nav aria-label="Primary navigation"><a href="#work">Work</a><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></nav><Link href="#contact" className="header-cta">Start a project</Link></header>

    <section className="hero section-shell"><div className="hero-stamp">MELLA<br />SOFTWARE<br />SOLUTIONS<br /><span>EST. 2026</span></div><div className="hero-copy"><p className="eyebrow">Independent software studio · Addis Ababa</p><h1>Make the<br /><em>next thing.</em></h1><p className="hero-lede">We design, build, and run software products for people with something useful to put into the world.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Start a project <Arrow /></a><Link href="#work">See our work</Link></div></div><div className="hero-orbit" aria-hidden="true"><span>IDEA</span><i /><b>BUILD</b><i /><span>LIVE</span></div></section>

    <section id="work" className="work-section section-shell"><div className="section-intro"><p className="eyebrow">Selected work / 04</p><h2>Things we&apos;ve<br /><em>made useful.</em></h2><p>From first thought to daily tool.</p></div><div className="work-grid">{work.map(([name, meta, copy], i) => <article className={`work-item item-${i + 1}`} key={name}><div className="project-visual"><span>0{i + 1}</span><div className="visual-mark">{i === 0 ? 'A' : i === 1 ? '＋' : i === 2 ? '◌' : '↗'}</div></div><p className="card-meta">{meta}</p><h3>{name}</h3><p>{copy}</p></article>)}</div><Link href="#contact">View all work</Link></section>

    <section id="services" className="services-section"><div className="section-shell services-layout"><div><p className="eyebrow">What we do</p><h2>Good software<br /><em>feels obvious.</em></h2></div><div><p className="large-copy">We turn complicated problems into calm, capable products — then help them get better.</p><div className="service-list">{services.map((service, i) => <div key={service}><span>0{i + 1}</span><strong>{service}</strong><Arrow /></div>)}</div><Link href="#contact">Explore our services</Link></div></div></section>

    <section className="split-section"><div className="split-panel owned"><p className="eyebrow">Our products</p><h2>Built with<br /><em>skin in it.</em></h2><p>We build, launch, and operate our own products. The lessons make every client project sharper.</p><Link href="#case-study">Open AdVouch</Link></div><div className="split-panel delivered"><p className="eyebrow">Our partnerships</p><h2>Your problem.<br /><em>Our team.</em></h2><p>Software built around your business — from a focused first release to an ongoing product team.</p><Link href="#contact">Work with us</Link></div></section>

    <section className="process-section section-shell"><div className="section-intro"><p className="eyebrow">The Mella method</p><h2>Less theatre.<br />More shipping.</h2></div><div className="process-grid">{process.map(([num, title, copy]) => <article key={num}><span className="process-number">{num}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

    <section id="case-study" className="case-section section-shell"><div className="case-head"><div><p className="eyebrow">Featured case study · In-house · Live</p><h2>AdVouch</h2><p className="large-copy">Advertising with a<br /><em>little more proof.</em></p></div><a className="button button-dark" href="#contact">Open AdVouch <Arrow /></a></div><div className="case-visual"><div className="case-screen"><div className="case-nav"><b>AdVouch</b><span>Discover Ads　 Businesses　 Campaigns　 Identity　 Payments</span></div><div className="case-body"><p>DISCOVER ADS</p><h3>Advertising<br />you can trust.</h3><div className="case-cards"><i /><i /><i /></div></div></div></div><div className="case-triad"><div><span>The problem</span><p>Informal advertising made trust, identity, and campaign payments difficult to verify.</p></div><div><span>The product</span><p>Discover Ads · Businesses · Campaigns · Identity · Payments</p></div><div><span>The result</span><p>A live product built and operated by Mella.</p></div></div></section>

    <section id="about" className="about-section section-shell"><div><p className="eyebrow">About Mella</p><h2>Small team.<br /><em>Big follow-through.</em></h2></div><div><p className="large-copy">Mella Software Solutions PLC builds software products under its own name and works with companies that need a team to design, build, and support their software.</p><p>We&apos;re small enough that you know who is doing the work.</p><Link href="#contact">About Mella</Link></div></section>
    <section id="contact" className="contact-section"><div className="section-shell contact-layout"><div><p className="eyebrow">Have a good one?</p><h2>Let&apos;s make<br /><em>it real.</em></h2></div><div><p className="large-copy">Tell us what you&apos;re building, what problem you&apos;re solving, and where you are today.</p><a className="button button-light" href="mailto:hello@mellasoftware.com">Start a project <Arrow /></a><p className="contact-details"><b>hello@mellasoftware.com</b><br />Addis Ababa, Ethiopia<br />Monday–Friday · 09:00–18:00 EAT</p></div></div></section>
    <footer className="footer section-shell"><div><a className="brand" href="#top">Mella<span>.</span></a><p>Make the next thing.</p></div><div className="footer-links"><a href="#work">Work</a><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></div><div className="footer-end"><span>Privacy · Terms</span><span>© 2026 Mella Software Solutions PLC</span></div></footer>
  </main>
}
